default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

# local PC
development:
  <<: *default
  database: db/development.sqlite3

# Test ç”¨
test:
  <<: *default
  database: db/test.sqlite3
  
production:
  <<: *default
  adapter: postgresql
  database: pjt_firstsns_production
  encoding: utf8
