default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

# local PC
development:
  <<: *default
  database: db/development.sqlite3

# Test 用
test:
  <<: *default
  database: db/test.sqlite3
  
production:
  adapter: postgresql
  # heroku addons:create heroku-postgresql:hobby-devのurl
  url: <%= ENV['DATABASE_URL'] %> 
  database: pjt_firstsns_production
  encoding: utf8
